export default function MethodologyPage() {
  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1>Methodology</h1>
          <p>
            This interface visualizes precomputed market analytics generated by the ThothMind backend.
          </p>
        </div>
      </div>

      <div className="content-grid single">
        <section className="card">
          <h2>Pipeline logic</h2>
          <p>
            The system selects a curated research universe, materializes a separate dataset,
            runs batch multi-ticker suite experiments, aggregates run-level metrics, and then
            exposes prepared JSON artifacts for frontend visualization.
          </p>
          <p>
            Heavy calculations are executed offline in Python. The frontend does not retrain
            or recompute the market universe in real time. It focuses on browsing, comparing,
            and interpreting already prepared results.
          </p>
        </section>

        <section className="card">
          <h2>Key metrics</h2>
          <p><strong>Return %</strong> reflects strategy-level aggregate performance for a suite run.</p>
          <p><strong>Sharpe</strong> summarizes risk-adjusted efficiency.</p>
          <p><strong>Max drawdown %</strong> measures the deepest historical decline.</p>
          <p><strong>p-value</strong> reflects statistical evidence in comparative evaluation and should be interpreted carefully.</p>
          <p><strong>Defense-ready score</strong> is currently an aggregate ranking metric rather than a strict scientific acceptance criterion.</p>
        </section>
      </div>
    </div>
  );
}
