import { useEffect, useMemo, useState } from "react";
import type { SuiteRun, TopRun } from "../shared/types/api";
import {
  loadSuiteRuns,
  loadTopByReturn,
  loadTopDefenseReady,
} from "../services/dataLoader";
import { adaptSuiteRuns, adaptTopRuns } from "../services/adapters";
import KpiCard from "../widgets/kpi/KpiCard";

function fmt(value: number | null | undefined, digits = 2) {
  return typeof value === "number" ? value.toFixed(digits) : "—";
}

export default function OverviewPage() {
  const [suiteRuns, setSuiteRuns] = useState<SuiteRun[]>([]);
  const [topReturn, setTopReturn] = useState<TopRun[]>([]);
  const [topDefense, setTopDefense] = useState<TopRun[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function bootstrap() {
      setLoading(true);

      const [suiteRaw, topReturnRaw, topDefenseRaw] = await Promise.all([
        loadSuiteRuns(),
        loadTopByReturn(),
        loadTopDefenseReady(),
      ]);

      setSuiteRuns(adaptSuiteRuns(suiteRaw));
      setTopReturn(adaptTopRuns(topReturnRaw));
      setTopDefense(adaptTopRuns(topDefenseRaw));
      setLoading(false);
    }

    bootstrap();
  }, []);

  const stats = useMemo(() => {
    const runCount = suiteRuns.length;

    const bestReturnRow =
      suiteRuns
        .filter((r) => typeof r.return_metric_pct === "number")
        .sort((a, b) => (b.return_metric_pct ?? -Infinity) - (a.return_metric_pct ?? -Infinity))[0] ??
      null;

    const bestDefenseRow =
      suiteRuns
        .filter((r) => typeof r.defense_ready_score === "number")
        .sort(
          (a, b) =>
            (b.defense_ready_score ?? -Infinity) - (a.defense_ready_score ?? -Infinity)
        )[0] ?? null;

    const maxTickers = suiteRuns.reduce(
      (acc, row) => Math.max(acc, row.n_suite_tickers || 0),
      0
    );

    const medianSharpe = (() => {
      const values = suiteRuns
        .map((row) => row.sharpe)
        .filter((v): v is number => typeof v === "number")
        .sort((a, b) => a - b);

      if (!values.length) return null;
      const mid = Math.floor(values.length / 2);
      return values.length % 2 === 0
        ? (values[mid - 1] + values[mid]) / 2
        : values[mid];
    })();

    const stages = Array.from(new Set(suiteRuns.map((r) => r.stage))).filter(Boolean);
    const configs = Array.from(new Set(suiteRuns.map((r) => r.config))).filter(Boolean);

    return {
      runCount,
      bestReturnRow,
      bestDefenseRow,
      maxTickers,
      medianSharpe,
      stages,
      configs,
    };
  }, [suiteRuns]);

  return (
    <div className="page">
      <section className="hero hero--premium">
        <div className="hero__content">
          <div className="hero__eyebrow">Institutional market intelligence layer</div>
          <h1 className="hero__title">ThothMind Research Terminal</h1>
          <p className="hero__description">
            A thesis-grade analytical interface for exploring precomputed multi-ticker
            forecasting experiments, ranking suite configurations, and interpreting
            market research outputs generated by the offline ThothMind backend.
          </p>

          <div className="hero__chips">
            <span className="hero-chip">M8 true multi</span>
            <span className="hero-chip">Curated universe</span>
            <span className="hero-chip">Offline batch backend</span>
            <span className="hero-chip">React research frontend</span>
          </div>
        </div>

        <div className="hero__sidecard hero__sidecard--premium">
          <div className="hero__sidecard-label">System snapshot</div>
          <div className="hero__sidecard-grid">
            <div>
              <div className="hero__metric-label">Suite runs</div>
              <div className="hero__metric-value">{stats.runCount}</div>
            </div>
            <div>
              <div className="hero__metric-label">Universe size</div>
              <div className="hero__metric-value">{stats.maxTickers}</div>
            </div>
            <div>
              <div className="hero__metric-label">Best return</div>
              <div className="hero__metric-value">
                {fmt(stats.bestReturnRow?.return_metric_pct)}%
              </div>
            </div>
            <div>
              <div className="hero__metric-label">Median sharpe</div>
              <div className="hero__metric-value">{fmt(stats.medianSharpe, 3)}</div>
            </div>
          </div>
        </div>
      </section>

      <section className="snapshot-strip">
        <div className="snapshot-card">
          <div className="snapshot-card__label">Loaded configs</div>
          <div className="snapshot-card__value">{stats.configs.length}</div>
          <div className="snapshot-card__meta">{stats.configs.join(", ") || "—"}</div>
        </div>

        <div className="snapshot-card">
          <div className="snapshot-card__label">Stages present</div>
          <div className="snapshot-card__value">{stats.stages.length}</div>
          <div className="snapshot-card__meta">{stats.stages.join(", ") || "—"}</div>
        </div>

        <div className="snapshot-card">
          <div className="snapshot-card__label">Best suite config</div>
          <div className="snapshot-card__value">
            {stats.bestReturnRow?.config ?? "—"}
          </div>
          <div className="snapshot-card__meta">
            Return {fmt(stats.bestReturnRow?.return_metric_pct)}% • Sharpe{" "}
            {fmt(stats.bestReturnRow?.sharpe, 4)}
          </div>
        </div>

        <div className="snapshot-card">
          <div className="snapshot-card__label">Defense-ready leader</div>
          <div className="snapshot-card__value">
            {stats.bestDefenseRow?.config ?? "—"}
          </div>
          <div className="snapshot-card__meta">
            Score {fmt(stats.bestDefenseRow?.defense_ready_score, 3)} • p-value{" "}
            {fmt(stats.bestDefenseRow?.p_value_one_sided, 4)}
          </div>
        </div>
      </section>

      {loading ? <div className="empty-state">Loading research snapshot…</div> : null}

      <div className="kpi-grid">
        <KpiCard
          label="Suite runs"
          value={String(stats.runCount)}
          hint="Loaded from suite-level index"
          accent="blue"
        />
        <KpiCard
          label="Best return %"
          value={fmt(stats.bestReturnRow?.return_metric_pct)}
          hint="Top suite-level result"
          accent="cyan"
        />
        <KpiCard
          label="Best defense score"
          value={fmt(stats.bestDefenseRow?.defense_ready_score, 3)}
          hint="Current ranking metric"
          accent="amber"
        />
        <KpiCard
          label="Max universe size"
          value={String(stats.maxTickers)}
          hint="Tickers inside one suite run"
          accent="blue"
        />
      </div>

      <div className="intelligence-grid intelligence-grid--overview">
        <section className="terminal-card terminal-card--featured">
          <div className="section-label">Research brief</div>
          <h2 className="section-title">Why this interface exists</h2>
          <p className="section-text">
            ThothMind separates heavy market computation from the visual layer.
            The backend performs long-running batch calculations and stores structured
            artifacts, while the frontend turns them into a stable, interpretable
            research terminal for defense and analytical demonstration.
          </p>

          <div className="research-annotation-grid">
            <div className="research-annotation">
              <div className="research-annotation__label">Backend mode</div>
              <div className="research-annotation__value">Offline batch analytics</div>
              <div className="research-annotation__text">
                ML and backtest computations are precomputed in Python and exported as
                suite-level and per-ticker artifacts.
              </div>
            </div>

            <div className="research-annotation">
              <div className="research-annotation__label">Frontend role</div>
              <div className="research-annotation__value">Interpretation layer</div>
              <div className="research-annotation__text">
                The UI does not retrain models in real time. It focuses on comparison,
                ranking, inspection, and explanation of saved outputs.
              </div>
            </div>

            <div className="research-annotation">
              <div className="research-annotation__label">Demo objective</div>
              <div className="research-annotation__value">Defense-ready clarity</div>
              <div className="research-annotation__text">
                The interface is designed to show both aggregate suite intelligence and
                instrument-level diagnostics in a controlled live presentation.
              </div>
            </div>
          </div>
        </section>

        <section className="terminal-card">
          <div className="section-label">Return leaderboard</div>
          <h2 className="section-title">Top suite runs</h2>
          <div className="mini-list">
            {topReturn.length === 0 ? (
              <div className="empty-state">No top-by-return JSON loaded yet.</div>
            ) : (
              topReturn.slice(0, 5).map((row, idx) => (
                <div className="mini-list__item" key={`${row.config}-${idx}`}>
                  <div>
                    <div className="mini-list__title">{row.config}</div>
                    <div className="mini-list__meta">
                      {row.ticker} • {row.n_suite_tickers ?? 0} tickers
                    </div>
                  </div>
                  <div className="mini-list__value">{fmt(row.return_metric_pct)}%</div>
                </div>
              ))
            )}
          </div>
        </section>

        <section className="terminal-card">
          <div className="section-label">Ranking heuristic</div>
          <h2 className="section-title">Defense-ready leaderboard</h2>
          <div className="mini-list">
            {topDefense.length === 0 ? (
              <div className="empty-state">No defense-ready JSON loaded yet.</div>
            ) : (
              topDefense.slice(0, 5).map((row, idx) => (
                <div className="mini-list__item" key={`${row.config}-${idx}`}>
                  <div>
                    <div className="mini-list__title">{row.config}</div>
                    <div className="mini-list__meta">
                      {row.ticker} • p-value {fmt(row.p_value_one_sided, 4)}
                    </div>
                  </div>
                  <div className="mini-list__value">
                    {fmt(row.defense_ready_score, 3)}
                  </div>
                </div>
              ))
            )}
          </div>
        </section>
      </div>
    </div>
  );
}