import { useEffect, useMemo, useState } from "react";
import type {
  CuratedManifest,
  SuiteRun,
  SuiteTickerResult,
  TopRun,
} from "../shared/types/api";
import {
  loadCuratedManifest,
  loadSuiteRuns,
  loadSuiteTickerResults,
  loadTopByReturn,
  loadTopDefenseReady,
} from "../services/dataLoader";
import {
  adaptSuiteRuns,
  adaptSuiteTickerResults,
  adaptTopRuns,
} from "../services/adapters";
import KpiCard from "../widgets/kpi/KpiCard";
import SuiteReturnChart from "../widgets/charts/SuiteReturnChart";
import SuiteRiskChart from "../widgets/charts/SuiteRiskChart";
import ReturnDrawdownScatterChart from "../widgets/charts/ReturnDrawdownScatterChart";

function fmt(value: number | null | undefined, digits = 2) {
  return typeof value === "number" ? value.toFixed(digits) : "—";
}

export default function OverviewPage() {
  const [suiteRuns, setSuiteRuns] = useState<SuiteRun[]>([]);
  const [tickerRows, setTickerRows] = useState<SuiteTickerResult[]>([]);
  const [topReturn, setTopReturn] = useState<TopRun[]>([]);
  const [topDefense, setTopDefense] = useState<TopRun[]>([]);
  const [manifest, setManifest] = useState<CuratedManifest | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function bootstrap() {
      setLoading(true);

      const [suiteRaw, tickerRaw, topReturnRaw, topDefenseRaw, manifestRaw] =
        await Promise.all([
          loadSuiteRuns(),
          loadSuiteTickerResults(),
          loadTopByReturn(),
          loadTopDefenseReady(),
          loadCuratedManifest(),
        ]);

      setSuiteRuns(adaptSuiteRuns(suiteRaw));
      setTickerRows(adaptSuiteTickerResults(tickerRaw));
      setTopReturn(adaptTopRuns(topReturnRaw));
      setTopDefense(adaptTopRuns(topDefenseRaw));
      setManifest(manifestRaw);
      setLoading(false);
    }

    bootstrap();
  }, []);

  const stats = useMemo(() => {
    const runCount = suiteRuns.length;

    const bestReturnRow =
      suiteRuns
        .filter((r) => typeof r.return_metric_pct === "number")
        .sort((a, b) => (b.return_metric_pct ?? -Infinity) - (a.return_metric_pct ?? -Infinity))[0] ??
      null;

    const bestDefenseRow =
      suiteRuns
        .filter((r) => typeof r.defense_ready_score === "number")
        .sort(
          (a, b) =>
            (b.defense_ready_score ?? -Infinity) - (a.defense_ready_score ?? -Infinity)
        )[0] ?? null;

    const bestSharpeRow =
      suiteRuns
        .filter((r) => typeof r.sharpe === "number")
        .sort((a, b) => (b.sharpe ?? -Infinity) - (a.sharpe ?? -Infinity))[0] ?? null;

    const maxTickers = suiteRuns.reduce(
      (acc, row) => Math.max(acc, row.n_suite_tickers || 0),
      0
    );

    const medianSharpe = (() => {
      const values = suiteRuns
        .map((row) => row.sharpe)
        .filter((v): v is number => typeof v === "number")
        .sort((a, b) => a - b);

      if (!values.length) return null;
      const mid = Math.floor(values.length / 2);
      return values.length % 2 === 0
        ? (values[mid - 1] + values[mid]) / 2
        : values[mid];
    })();

    const configs = Array.from(new Set(suiteRuns.map((r) => r.config))).filter(Boolean);
    const stages = Array.from(new Set(suiteRuns.map((r) => r.stage))).filter(Boolean);
    const uniqueTickers = Array.from(new Set(tickerRows.map((r) => r.ticker))).filter(Boolean);

    const okTickerRows = tickerRows.filter((r) => (r.status ?? "").toLowerCase() === "ok").length;

    const minPValue = (() => {
      const values = suiteRuns
        .map((r) => r.p_value_one_sided)
        .filter((v): v is number => typeof v === "number");
      if (!values.length) return null;
      return Math.min(...values);
    })();

    return {
      runCount,
      bestReturnRow,
      bestDefenseRow,
      bestSharpeRow,
      maxTickers,
      medianSharpe,
      configs,
      stages,
      uniqueTickers,
      okTickerRows,
      minPValue,
    };
  }, [suiteRuns, tickerRows]);

  return (
    <div className="page">
      <section className="hero hero--premium">
        <div className="hero__content">
          <div className="hero__eyebrow">Institutional market intelligence layer</div>
          <h1 className="hero__title">ThothMind Research Terminal</h1>
          <p className="hero__description">
            A thesis-grade analytical interface for exploring precomputed multi-ticker
            forecasting experiments, ranking suite configurations, and interpreting
            market research outputs generated by the offline ThothMind backend.
          </p>

          <div className="hero__chips">
            <span className="hero-chip">M8 true multi</span>
            <span className="hero-chip">Curated universe</span>
            <span className="hero-chip">Offline batch backend</span>
            <span className="hero-chip">React research frontend</span>
          </div>
        </div>

        <div className="hero__sidecard hero__sidecard--premium">
          <div className="hero__sidecard-label">System snapshot</div>
          <div className="hero__sidecard-grid">
            <div>
              <div className="hero__metric-label">Suite runs</div>
              <div className="hero__metric-value">{stats.runCount}</div>
            </div>
            <div>
              <div className="hero__metric-label">Universe size</div>
              <div className="hero__metric-value">{stats.maxTickers}</div>
            </div>
            <div>
              <div className="hero__metric-label">Best return</div>
              <div className="hero__metric-value">
                {fmt(stats.bestReturnRow?.return_metric_pct)}%
              </div>
            </div>
            <div>
              <div className="hero__metric-label">Median sharpe</div>
              <div className="hero__metric-value">{fmt(stats.medianSharpe, 3)}</div>
            </div>
          </div>
        </div>
      </section>

      <section className="snapshot-strip">
        <div className="snapshot-card">
          <div className="snapshot-card__label">Loaded configs</div>
          <div className="snapshot-card__value">{stats.configs.length}</div>
          <div className="snapshot-card__meta">{stats.configs.join(", ") || "—"}</div>
        </div>

        <div className="snapshot-card">
          <div className="snapshot-card__label">Stages present</div>
          <div className="snapshot-card__value">{stats.stages.length}</div>
          <div className="snapshot-card__meta">{stats.stages.join(", ") || "—"}</div>
        </div>

        <div className="snapshot-card">
          <div className="snapshot-card__label">Ticker diagnostics</div>
          <div className="snapshot-card__value">{stats.uniqueTickers.length}</div>
          <div className="snapshot-card__meta">
            {stats.okTickerRows} valid rows across suite-level ticker outputs
          </div>
        </div>

        <div className="snapshot-card">
          <div className="snapshot-card__label">Defense-ready leader</div>
          <div className="snapshot-card__value">
            {stats.bestDefenseRow?.config ?? "—"}
          </div>
          <div className="snapshot-card__meta">
            Score {fmt(stats.bestDefenseRow?.defense_ready_score, 3)} • p-value{" "}
            {fmt(stats.bestDefenseRow?.p_value_one_sided, 4)}
          </div>
        </div>
      </section>

      <section className="dataset-panel">
        <div className="dataset-panel__header">
          <div>
            <div className="section-label">Dataset metadata</div>
            <h2 className="section-title">Curated universe snapshot</h2>
          </div>
          <div className="dataset-status">
            {manifest ? "manifest loaded" : "manifest missing"}
          </div>
        </div>

        <div className="dataset-panel__grid">
          <div className="dataset-metric">
            <div className="dataset-metric__label">Stocks</div>
            <div className="dataset-metric__value">{manifest?.stocks_count ?? "—"}</div>
          </div>
          <div className="dataset-metric">
            <div className="dataset-metric__label">ETFs</div>
            <div className="dataset-metric__value">{manifest?.etfs_count ?? "—"}</div>
          </div>
          <div className="dataset-metric">
            <div className="dataset-metric__label">Expected</div>
            <div className="dataset-metric__value">{manifest?.total_expected ?? "—"}</div>
          </div>
          <div className="dataset-metric">
            <div className="dataset-metric__label">Copied</div>
            <div className="dataset-metric__value">{manifest?.total_copied ?? "—"}</div>
          </div>
        </div>

        <div className="dataset-panel__footer">
          <div className="dataset-panel__meta">
            Output root: {manifest?.output_root ?? "not available"}
          </div>
          <div className="dataset-panel__meta">
            Missing files: {manifest?.missing_files_count ?? "—"}
          </div>
        </div>
      </section>

      {loading ? <div className="empty-state">Loading research snapshot…</div> : null}

      <div className="kpi-grid">
        <KpiCard
          label="Suite runs"
          value={String(stats.runCount)}
          hint="Loaded from suite-level index"
          accent="blue"
        />
        <KpiCard
          label="Best return %"
          value={fmt(stats.bestReturnRow?.return_metric_pct)}
          hint="Top suite-level result"
          accent="cyan"
        />
        <KpiCard
          label="Best defense score"
          value={fmt(stats.bestDefenseRow?.defense_ready_score, 3)}
          hint="Current ranking metric"
          accent="amber"
        />
        <KpiCard
          label="Max universe size"
          value={String(stats.maxTickers)}
          hint="Tickers inside one suite run"
          accent="blue"
        />
      </div>

      <section className="insight-banner">
        <div className="insight-pill">
          <div className="insight-pill__label">Best raw return</div>
          <div className="insight-pill__value">{stats.bestReturnRow?.config ?? "—"}</div>
        </div>
        <div className="insight-pill">
          <div className="insight-pill__label">Best risk-adjusted profile</div>
          <div className="insight-pill__value">{stats.bestSharpeRow?.config ?? "—"}</div>
        </div>
        <div className="insight-pill">
          <div className="insight-pill__label">Minimum p-value</div>
          <div className="insight-pill__value">{fmt(stats.minPValue, 4)}</div>
        </div>
        <div className="insight-pill insight-pill--warning">
          <div className="insight-pill__label">Research caution</div>
          <div className="insight-pill__value">
            {typeof stats.minPValue === "number" && stats.minPValue <= 0.1
              ? "Some significance evidence present"
              : "No strong statistical superiority evidence"}
          </div>
        </div>
      </section>

      <div className="chart-grid chart-grid--triple">
        <SuiteReturnChart rows={suiteRuns} />
        <SuiteRiskChart rows={suiteRuns} />
        <ReturnDrawdownScatterChart rows={suiteRuns} />
      </div>

      <div className="intelligence-grid intelligence-grid--overview">
        <section className="terminal-card terminal-card--featured">
          <div className="section-label">Research brief</div>
          <h2 className="section-title">Why this interface exists</h2>
          <p className="section-text">
            ThothMind separates heavy market computation from the visual layer.
            The backend performs long-running batch calculations and stores structured
            artifacts, while the frontend turns them into a stable, interpretable
            research terminal for defense and analytical demonstration.
          </p>

          <div className="research-annotation-grid">
            <div className="research-annotation">
              <div className="research-annotation__label">Backend mode</div>
              <div className="research-annotation__value">Offline batch analytics</div>
              <div className="research-annotation__text">
                ML and backtest computations are precomputed in Python and exported as
                suite-level and per-ticker artifacts.
              </div>
            </div>

            <div className="research-annotation">
              <div className="research-annotation__label">Frontend role</div>
              <div className="research-annotation__value">Interpretation layer</div>
              <div className="research-annotation__text">
                The UI does not retrain models in real time. It focuses on comparison,
                ranking, inspection, and explanation of saved outputs.
              </div>
            </div>

            <div className="research-annotation">
              <div className="research-annotation__label">Demo objective</div>
              <div className="research-annotation__value">Defense-ready clarity</div>
              <div className="research-annotation__text">
                The interface is designed to show both aggregate suite intelligence and
                instrument-level diagnostics in a controlled live presentation.
              </div>
            </div>
          </div>
        </section>

        <section className="terminal-card">
          <div className="section-label">Return leaderboard</div>
          <h2 className="section-title">Top suite runs</h2>
          <div className="mini-list">
            {topReturn.length === 0 ? (
              <div className="empty-state">No top-by-return JSON loaded yet.</div>
            ) : (
              topReturn.slice(0, 5).map((row, idx) => (
                <div className="mini-list__item" key={`${row.config}-${idx}`}>
                  <div>
                    <div className="mini-list__title">{row.config}</div>
                    <div className="mini-list__meta">
                      {row.ticker} • {row.n_suite_tickers ?? 0} tickers
                    </div>
                  </div>
                  <div className="mini-list__value">{fmt(row.return_metric_pct)}%</div>
                </div>
              ))
            )}
          </div>
        </section>

        <section className="terminal-card">
          <div className="section-label">Ranking heuristic</div>
          <h2 className="section-title">Defense-ready leaderboard</h2>
          <div className="mini-list">
            {topDefense.length === 0 ? (
              <div className="empty-state">No defense-ready JSON loaded yet.</div>
            ) : (
              topDefense.slice(0, 5).map((row, idx) => (
                <div className="mini-list__item" key={`${row.config}-${idx}`}>
                  <div>
                    <div className="mini-list__title">{row.config}</div>
                    <div className="mini-list__meta">
                      {row.ticker} • p-value {fmt(row.p_value_one_sided, 4)}
                    </div>
                  </div>
                  <div className="mini-list__value">
                    {fmt(row.defense_ready_score, 3)}
                  </div>
                </div>
              ))
            )}
          </div>
        </section>
      </div>
    </div>
  );
}